### PR TITLE
Return `_integerToDecimal` as `0.01` for anything between `0,00000001` to `0.009`

### PR DESCRIPTION
**Pull request by maarteNNNN**

### CODE REVIEW

**Comment by maarteNNNN** [comment]
After some consideration I'm going to do this differently

**Comment by jondubois** [comment]
I don't know if I like this solution better. It's more misleading becuase `0.0001` is closer to `0.00` than it is from `0.01`,

**Comment by maarteNNNN** [comment]
What about adjusting the decimals accordingly it if it's `< 0.01` e.g. `0.001` and `0.000001`?

**Comment by jondubois** [comment]
Maybe we can check how other platforms handle this problem. How does Lisk handle it?

**Comment by maarteNNNN** [comment]
image
Lisk shows decimals as is, not rounded.

**Pull request merged**
